[package]
name = "annoying_prefix_remover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12"
native-dialog = "0.7.0"
